### ISSUE TITLE
No persistence saves happening on server cloud save

### ISSUE THREAD

**Issue by Will-Nichols** [ALiVEOS/ALiVE.OS#565]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [X] Have you attached an unbinarized SQM?
* [X] Have you attached your RPT (If the issue relates to data, also attach Server RPT and ALiVE Plugin Log)?
* [X] Have you attached screenshots of the Parameters set on the offending Module?

[ALiVE Required module](https://steamcommunity.com/sharedfiles/filedetails/?id=1589296835)
[ALiVE Data Module](https://steamcommunity.com/sharedfiles/filedetails/?id=1589296765)
[ALiVE Player Options](https://steamcommunity.com/sharedfiles/filedetails/?id=1589296806)

### Description

When starting to run a server save and exit the mission ends instead of pulling up the ALiVE tablet and allowing you to do the save process.

I have attempted a connection to the War Room via a browser on the dedicated server and it connects as it should do all the time. Put related comments in Issue #545 .

### Steps to Reproduce

1. Load mission
2. Play around some and drop in some crates and other stuff and move vehicles around and enter crates to make them persistent
3. Login to admin functions and hit server save and exit and see what happens

**Expected behavior:** I expect the server to actually save the items and return me to the same time as when the server was saved in the game with the boxes and other things in the same places.

**Actual behavior:** It reloads the mission from the exact start time as specified in the editor for when the mission is set to begin and nothing that was placed down earlier is there to use.

[RPT for Task Force Red ALiVE Persistence Test](https://www.dropbox.com/s/f4dypgf270lanye/ALiVE%20Persistence%20Test%20with%20CBA%20and%20ALiVE.rpt?dl=0) with only CBA and ALiVE as the mods.
[Video linked here](https://www.youtube.com/watch?v=o-PbxLmPi2A&feature=youtu.be)
[Basic_Repro_Test_Mission_ALiVE_Persistence](https://www.dropbox.com/s/efpm8jzwf5vn0mn/Basic_Repro_Test_Mission_ALiVE_Persistence.Altis.pbo?dl=0) Test for Task Force Red Server

**Comment by secit** [comment]
Finding this in your RPT log:
`CallExtension 'ALiVEPlugIn' could not be found`

This indicates it couldn't load the ALiVEPlugIn_x64.dll located in your @AliveServer folder, which is crucial for persistence.

Double check your path for `@AliveServer`. I noticed you've placed all other mods in the `!mods`-path, but not for `@AliveServer'.

**Comment by Will-Nichols** [comment]
Checking on that now and none of our guys can give me an answer on how those get called. I also just discovered that our server name wasn't the same as what we setup for the alive.cfg file either.

**Comment by Will-Nichols** [comment]
OK @secit I found part of the problem. Someone had changed the name of the server away from what it was supposed to be named in the server.cfg file. 

- Found one possible issue where whoever had copied over the files for the @aliveserver mod had actually placed it as @aliveserver -> @allveserver -> then the .dll files inside the second folder inside the first one. So its no wonder that the .dll files were not running. I have fixed that as well as changing the name back to TFRedMilsim for our main server. 

- Also still have the issue where the ALiVEPlugin isn't located all the time in the RPT.
- However; I just ran a persistence test on our main mission server and the items that were gathered by the guys were not saved; other than the box I placed down and accessed to store weapons and backpacks and 2 extra vehicles that they had moved. Not sure what the reason is for the weapons disappearing but they were stored in backpacks and placed in a crate. 

Other than that being the problem everything looks good so far; more testing will happen to ensure that was all we had a problem with.

**Comment by secit** [comment]
Did you remove the second folder and put the dll-files inside the first one?
Is it the same error message inside the RPT log? `CallExtension 'ALiVEPlugIn' could not be found`
If yes, then Arma is still not able to find/load the dll-files.

When you start the mission the dll-file should create a separate logfile inside @AliveServer-folder named aliveplugin_(date-time here).txt
If there is no logfile, then the dll was never loaded and thus persistence will not work.

**Comment by Will-Nichols** [comment]
Yes I removed the second folder and replaced the .dll files correctly. I did that before I ran the final persistence test which is when I discovered the the boxes never saved the gear that had been placed in them. 

Here is the segment of the RPT related to ALiVE loading into the server:

`16:59:36      MMMMMMMMMM    MMMMMMMM.                    .MMMMMM.      . MMMMMM                 MMMMMMMM   
16:59:36     IMMMMMMMMMM    MMMMMMMM.                    .MMMMMM:      .MMMMMMM                .MMMMMMMM.   
16:59:36 
16:59:36 ALiVE Global INIT
16:59:36 ALiVE Global Init Timer Started
16:59:36 ALiVE [m_0|30] Module ALiVE_sys_data INIT
16:59:36 CallExtension loaded: ALiVEPlugIn (D:\Arma 3 Servers\Milsim\@AliveServer\ALiVEPlugIn_x64.dll) [2.1.0.0] [2.1.0.0]

16:59:37 ALIVE_SYS_DATA START PLUGIN: ["StartALiVE","OK","Performance Monitor: Disabled"]
16:59:37 DATA: Attempting to load ALiVE web services config.
16:59:37 ALiVE-7.31 CONNECTED TO CLOUD SERVICE AND PERFDATA IS ALLOWED
16:59:37 DATA: Loading data dictionary dictionary_TFRed_Operation_Tanoa_Takedown_updated.
16:59:37 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','sys_data/dictionary_TFRed_Operation_Tanoa_Takedown_updated','']
16:59:37 DATA: No data dictionary found, might be new mission
16:59:37 DATA: Starting AAR system.
16:59:37 DATA: Waiting for global DISABLED variable...
16:59:37 DATA: SYS DATA enabled: true
16:59:37 DATA: Starting stats system.
16:59:37 "Operation: Tanoa Takedown"
16:59:37 Adding ACE Stats EHs to player <NULL-object>
16:59:37 ALiVE [m_0|30] Module ALiVE_sys_data INIT COMPLETE TIME:  0.806
16:59:37 ALiVE SYS_DATA - ASYNC WRITE LOOP STARTING
16:59:37 ALiVE [m_1|40] Module ALiVE_require INIT
16:59:37 ALiVE - Auto Pause Modules Initialising...
16:59:37 ALiVE [m_2|41] Module ALiVE_sys_newsfeed INIT
16:59:37 ALiVE [m_2|41] Module ALiVE_sys_newsfeed INIT COMPLETE TIME:  0
16:59:37 ALiVE [m_3|42] Module ALiVE_sys_adminactions INIT
16:59:37 ALiVE [m_3|42] Module ALiVE_sys_adminactions INIT COMPLETE TIME:  0
16:59:37 ALiVE [m_4|43] Module ALiVE_SYS_spotrep INIT
16:59:37 DATA: Loading spot report data.
16:59:38 ALiVE AI Distributor not enabled (mode: false).
16:59:38 ALiVE [m_5|45] Module ALiVE_SYS_LOGISTICS INIT
16:59:38 ALiVE [m_6|44] Module ALiVE_SYS_marker INIT
16:59:38 DATA: Loading marker data.
16:59:38 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','sys_spotrep/TFRed_Operation_Tanoa_Takedown_updated','']
16:59:38  ------------------ Inspecting Hash -------------------- 
16:59:38  ------------------ Inspection Complete -------------------- 
16:59:38 ALiVE [m_4|43] Module ALiVE_SYS_spotrep INIT COMPLETE TIME:  0.646004
16:59:38 ALiVE staticData Handler loading started
16:59:39 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','sys_marker/TFRed_Operation_Tanoa_Takedown_updated','']
16:59:39  ------------------ Inspecting Hash -------------------- 
16:59:39  ------------------ Inspection Complete -------------------- 
16:59:39 ALiVE [m_6|44] Module ALiVE_SYS_marker INIT COMPLETE TIME:  0.632996
16:59:39 ALiVE SETTING UP MAP: Tanoa
16:59:39 MAP NOT INDEXED OR DEDI SERVER FILE LOAD... ALiVE LOADING MAP DATA: Tanoa
16:59:39 ALiVE SETTING UP MAP: tanoa
16:59:39 ALiVE staticData Handler loading finished
16:59:39 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','sys_logistics/TFRed_Operation_Tanoa_Takedown_updated','']
16:59:39  ------------------ Inspecting Hash -------------------- 
16:59:39  ------------------ Inspection Complete -------------------- 
16:59:39 ALiVE [m_5|45] Module ALiVE_SYS_LOGISTICS INIT COMPLETE TIME:  1.439
16:59:40 ALiVE [m_7|50] Module ALiVE_sys_aiskill INIT
16:59:40 ALiVE [m_7|50] Module ALiVE_sys_aiskill INIT COMPLETE TIME:  0.000999451
16:59:40 ALiVE [m_8|60] Module ALiVE_sys_profile INIT
16:59:40 ALiVE MAP BOUNDS: 15360
16:59:41 "ALiVE - Starting Garbage Collector..."
16:59:42 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','sys_profile/TFRed_Operation_Tanoa_Takedown_updated','']
16:59:42 ALiVE [m_8|60] Module ALiVE_sys_profile INIT COMPLETE TIME:  2.11
16:59:42 ALiVE [m_9|70] Module ALiVE_amb_civ_population INIT
16:59:42 ALiVE [m_9|70] Module ALiVE_amb_civ_population INIT COMPLETE TIME:  0.00400543
16:59:42 ALiVE [m_10|80] Module ALiVE_amb_civ_placement INIT
16:59:43 ALiVE [m_11|80] Module ALiVE_amb_civ_placement INIT
16:59:43 ALiVE [m_12|80] Module ALiVE_amb_civ_placement INIT
16:59:43 ALiVE [m_13|80] Module ALiVE_amb_civ_placement INIT
16:59:43 ALiVE [m_14|80] Module ALiVE_amb_civ_placement INIT
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:44 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
16:59:45 Strange convex component16 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
16:59:45 Strange convex component25 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
16:59:45 Strange convex component26 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
16:59:45 Strange convex component27 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
16:59:47 ALiVE [m_15|90] Module ALiVE_mil_placement INIT
16:59:47 ALiVE [m_16|90] Module ALiVE_mil_placement INIT
16:59:50 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:50 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:50 ALIVE AMBCP - Warning no locations found for placement, you need to include civilian locations within the TAOR marker
16:59:50 ALiVE [m_14|80] Module ALiVE_amb_civ_placement INIT COMPLETE TIME:  6.622
16:59:50 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:50 ALIVE AMBCP - Warning no locations found for placement, you need to include civilian locations within the TAOR marker
16:59:50 ALiVE [m_10|80] Module ALiVE_amb_civ_placement INIT COMPLETE TIME:  7.42
16:59:50 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:50 ALIVE AMBCP - Warning no locations found for placement, you need to include civilian locations within the TAOR marker
16:59:50 ALiVE [m_11|80] Module ALiVE_amb_civ_placement INIT COMPLETE TIME:  6.968
16:59:50 ALIVE AMBCP - Warning no locations found for placement, you need to include civilian locations within the TAOR marker
16:59:50 ALiVE [m_12|80] Module ALiVE_amb_civ_placement INIT COMPLETE TIME:  6.895
16:59:50 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:50 ALIVE AMBCP - Warning no locations found for placement, you need to include civilian locations within the TAOR marker
16:59:50 ALiVE [m_13|80] Module ALiVE_amb_civ_placement INIT COMPLETE TIME:  6.82899
16:59:51 ALiVE [m_17|100] Module ALiVE_civ_placement INIT
16:59:51 ALiVE [m_18|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_19|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_20|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_21|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_22|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_23|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_24|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_25|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_26|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_27|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_28|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_29|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_30|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_31|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_32|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_33|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_34|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_35|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_36|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_37|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_38|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_39|100] Module ALiVE_civ_placement INIT
16:59:51 ALiVE [m_40|100] Module ALiVE_mil_placement_custom INIT
16:59:51 ALiVE [m_41|100] Module ALiVE_mil_placement_custom INIT
16:59:51 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:51 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:51 ALiVE [m_17|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  0.778999
16:59:51 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:51 ALiVE [m_39|100] Module ALiVE_civ_placement INIT COMPLETE TIME:  0.838005
16:59:52 Warning: This version of ALiVE is build for A3 version: 186.145229. The server is running version: 188.145263. Please contact your server administrator and update to the latest ALiVE release version.
16:59:52 ALIVE MP - Warning no HQ locations found
16:59:54 ALiVE [m_15|90] Module ALiVE_mil_placement INIT COMPLETE TIME:  6.848
16:59:57 ALiVE [m_37|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.514
16:59:57 ALiVE [m_40|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.561
16:59:57 ALiVE [m_38|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.6
16:59:57 ALiVE [m_41|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.638
16:59:57 ALiVE [m_19|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.75
16:59:57 ALiVE [m_20|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.776
16:59:58 ALiVE [m_21|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.87901
16:59:58 ALiVE [m_35|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  6.903
16:59:58 ALiVE [m_23|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.077
16:59:58 ALiVE [m_24|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.114
16:59:58 ALiVE [m_29|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.274
16:59:58 ALiVE [m_30|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.311
16:59:58 ALiVE [m_26|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.429
16:59:58 ALiVE [m_31|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.464
16:59:58 ALiVE [m_33|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.515
16:59:58 ALiVE [m_28|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.605
16:59:58 ALiVE [m_18|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.745
16:59:58 ALiVE [m_22|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.76401
16:59:59 ALiVE [m_27|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  7.983
16:59:59 ALiVE [m_32|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  8.017
16:59:59 ALiVE [m_34|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  8.02
16:59:59 ALiVE [m_25|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  8.183
16:59:59 ALiVE [m_36|100] Module ALiVE_mil_placement_custom INIT COMPLETE TIME:  8.294
16:59:59 ALiVE [m_16|90] Module ALiVE_mil_placement INIT COMPLETE TIME:  12.154
17:00:01 ALiVE [m_42|180] Module ALiVE_mil_OPCOM INIT
17:00:01 ALiVE OPCOM Waiting for Virtual AI System...
17:00:01 [TIMER STARTED]
17:00:01 ALiVE [m_43|180] Module ALiVE_mil_OPCOM INIT
17:00:01 ALiVE OPCOM Waiting for Virtual AI System...
17:00:01 [TIMER STARTED]
17:00:01 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','mil_opcom/TFRed_Operation_Tanoa_Takedown_updated','']
17:00:01 [TIMER ENDED : 0.121002]
17:00:04 Warning: 3109 ms spent in callExtension calling name: "ALiVEPlugIn", function: "SendJSON ['GET','mil_opcom/TFRed_Operation_Tanoa_Takedown_updated-OPCOM_213913228-starting-forces','']"
17:00:04 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','mil_opcom/TFRed_Operation_Tanoa_Takedown_updated','']
17:00:04 [TIMER ENDED : 3.242]
17:00:04 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','mil_opcom/TFRed_Operation_Tanoa_Takedown_updated-OPCOM_213913228-starting-forces','']
17:00:05 ALiVE OPCOM created 37 new objectives!
17:00:05 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','mil_opcom/TFRed_Operation_Tanoa_Takedown_updated-OPCOM_119033012-starting-forces','']
17:00:05 ALiVE OPCOM created 22 new objectives!
17:00:05 ALiVE OPCOM EAST Initial analysis done...
17:00:05 OPCOM and TACOM EAST starting...
17:00:05 ALiVE [m_43|180] Module ALiVE_mil_OPCOM INIT COMPLETE TIME:  3.607
17:00:05 ALiVE OPCOM EAST Initial analysis done...
17:00:05 OPCOM and TACOM EAST starting...
17:00:05 ALiVE [m_42|180] Module ALiVE_mil_OPCOM INIT COMPLETE TIME:  3.81699
17:00:05 ALiVE [m_44|190] Module ALiVE_mil_ato INIT
17:00:05 ALiVE [m_45|190] Module ALiVE_mil_logistics INIT
17:00:05 ALiVE [m_46|190] Module ALiVE_mil_logistics INIT
17:00:05 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"not_found","reason":"missing"}
'] CMD: SendJSON ['GET','mil_ato/TFRed_Operation_Tanoa_Takedown_updated_ATO','']
17:00:05 ALiVE_fnc_HashGet retrieved wrong input [<null>,"nodes"] from ALiVE_fnc_ATO!
17:00:05 Error in expression <gs select 0;

} else {

_hqBuilding = ([_baseCluster,"nodes"] call ALiVE_fnc_has>
17:00:05   Error position: <_baseCluster,"nodes"] call ALiVE_fnc_has>
17:00:05   Error Undefined variable in expression: _basecluster
17:00:05 File \x\alive\addons\mil_ato\fnc_ATO.sqf [ALiVE_fnc_ATO], line 3201
17:00:06 ALiVE [m_47|200] Module ALiVE_SYS_playeroptions INIT
17:00:06 L Alpha 1-3:3 - Initialisation started...
17:00:06 ALiVE [m_48|202] Module ALiVE_sys_player INIT
17:00:06 ALiVE [m_48|202] Module ALiVE_sys_player INIT COMPLETE TIME:  0.00100708
17:00:06 ALiVE [m_49|201] Module ALiVE_SYS_viewdistance INIT
17:00:06 ALiVE [m_49|201] Module ALiVE_SYS_viewdistance INIT COMPLETE TIME:  0
17:00:06 ALiVE [m_50|203] Module ALiVE_sys_crewinfo INIT
17:00:06 ALiVE SYS CREWINFO - Feature turned off! Exiting...
17:00:06 ALiVE [m_50|203] Module ALiVE_sys_crewinfo INIT COMPLETE TIME:  0
17:00:06 ALiVE [m_51|204] Module ALiVE_sys_playertags INIT
17:00:06 ALiVE [m_51|204] Module ALiVE_sys_playertags INIT COMPLETE TIME:  0
17:00:06 L Alpha 1-3:3 - Initialisation Completed...
17:00:06 ALiVE [m_47|200] Module ALiVE_SYS_playeroptions INIT COMPLETE TIME:  0.00900269
17:00:06 ALiVE [m_1|40] Module ALiVE_require INIT COMPLETE TIME:  28.83
17:00:06 ALiVE Global INIT COMPLETE
17:00:06 ALiVE Global Init Timer Complete 29.95`

**Comment by Will-Nichols** [comment]
@secit It seems like the issue may be resolved right now but I am not 100% as there are several funny things happening with persistence saves. For now you can close this or we can just leave it open and take a look at it going forward.
